### PR TITLE
sorting.js tests

### PR DESCRIPTION
**Pull request by PyromaniacalGoose**
Added several more tests to sorting.tests.js testing the frontend sorting.js methods.
Tested for *most* edge cases, some where not possible to test for or simply too redundant.

Managed to get nearly 100% coverage on all parameters.

### CODE REVIEW

**Comment by demiguard** [comment]
Hey you are missing the changes to sorting.js that we talked about

**Comment by PyromaniacalGoose** [comment]
I figured I would add them to a seperate push to keep branches clean, but I just add them here instead then.

**Comment by demiguard** [comment]
image

dis how we do it

**Comment by PyromaniacalGoose** [comment]
🫡

**Comment by demiguard** [comment]
Btw, gider du kigge på at 'sign'e dine commits?

Du kan få vscode automatisk at signe dem

**Comment by PyromaniacalGoose** [comment]
Ja det skal jeg nok kigge på.

**Pull request merged**
